---
galaxy_info:
  author: Laura Grechenko (@lauragrechenko)
  description: "Single-task role wrapping dev_write_module"
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions: ["all"]
dependencies: []